import uuid
from decimal import Decimal
from typing import Any
from pydantic import BaseModel, Field

from src.core.constants import PaymentStatus


class GatewayPaymentUrlResult(BaseModel):
    payment_url: str = Field(..., description="Checkout redirect URL on Gateway")
    qr_code_url: str | None = Field(default=None, description="Optional QR code image or payment link")
    gateway_reference: str = Field(..., description="Transaction or session reference assigned by Gateway")


class GatewayWebhookResult(BaseModel):
    is_valid: bool = Field(..., description="Whether signature and checksum verification passed")
    booking_id: uuid.UUID = Field(..., description="Booking ID associated with this payment")
    gateway_transaction_id: str = Field(..., description="Transaction ID generated by the payment gateway")
    amount: Decimal = Field(..., description="Confirmed transaction amount")
    status: PaymentStatus = Field(..., description="Normalized payment status (SUCCESS / FAILED)")
    raw_data: dict[str, Any] = Field(default_factory=dict, description="Raw webhook payload from gateway")


class GatewayQueryResult(BaseModel):
    is_found: bool = Field(..., description="Whether transaction exists on the gateway")
    status: PaymentStatus = Field(..., description="Transaction status reported by gateway")
    gateway_transaction_id: str | None = Field(default=None, description="Gateway transaction reference")
    amount: Decimal | None = Field(default=None, description="Transaction amount")
    raw_data: dict[str, Any] = Field(default_factory=dict, description="Raw query response from gateway")
