// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/zentrix-app/zentrix-backend-go-temp/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockEvent) CreateEvent(ctx context.Context, venueID, title, description, bannerURL string) (entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, venueID, title, description, bannerURL)
	ret0, _ := ret[0].(entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEventMockRecorder) CreateEvent(ctx, venueID, title, description, bannerURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEvent)(nil).CreateEvent), ctx, venueID, title, description, bannerURL)
}

// CreateShowWithSeats mocks base method.
func (m *MockEvent) CreateShowWithSeats(ctx context.Context, eventID string, startTime, endTime time.Time, rows, cols int, price float64) (entity.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShowWithSeats", ctx, eventID, startTime, endTime, rows, cols, price)
	ret0, _ := ret[0].(entity.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShowWithSeats indicates an expected call of CreateShowWithSeats.
func (mr *MockEventMockRecorder) CreateShowWithSeats(ctx, eventID, startTime, endTime, rows, cols, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShowWithSeats", reflect.TypeOf((*MockEvent)(nil).CreateShowWithSeats), ctx, eventID, startTime, endTime, rows, cols, price)
}

// CreateVenue mocks base method.
func (m *MockEvent) CreateVenue(ctx context.Context, name, address string, capacity int) (entity.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVenue", ctx, name, address, capacity)
	ret0, _ := ret[0].(entity.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVenue indicates an expected call of CreateVenue.
func (mr *MockEventMockRecorder) CreateVenue(ctx, name, address, capacity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVenue", reflect.TypeOf((*MockEvent)(nil).CreateVenue), ctx, name, address, capacity)
}

// GetEventDetail mocks base method.
func (m *MockEvent) GetEventDetail(ctx context.Context, eventID string) (entity.Event, []entity.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventDetail", ctx, eventID)
	ret0, _ := ret[0].(entity.Event)
	ret1, _ := ret[1].([]entity.Show)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEventDetail indicates an expected call of GetEventDetail.
func (mr *MockEventMockRecorder) GetEventDetail(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventDetail", reflect.TypeOf((*MockEvent)(nil).GetEventDetail), ctx, eventID)
}

// GetShowSeats mocks base method.
func (m *MockEvent) GetShowSeats(ctx context.Context, showID string) ([]entity.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShowSeats", ctx, showID)
	ret0, _ := ret[0].([]entity.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShowSeats indicates an expected call of GetShowSeats.
func (mr *MockEventMockRecorder) GetShowSeats(ctx, showID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShowSeats", reflect.TypeOf((*MockEvent)(nil).GetShowSeats), ctx, showID)
}

// ListEvents mocks base method.
func (m *MockEvent) ListEvents(ctx context.Context, limit, offset int) ([]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventMockRecorder) ListEvents(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEvent)(nil).ListEvents), ctx, limit, offset)
}

// LockSeats mocks base method.
func (m *MockEvent) LockSeats(ctx context.Context, showID string, seatIDs []string, userID string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSeats", ctx, showID, seatIDs, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LockSeats indicates an expected call of LockSeats.
func (mr *MockEventMockRecorder) LockSeats(ctx, showID, seatIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSeats", reflect.TypeOf((*MockEvent)(nil).LockSeats), ctx, showID, seatIDs, userID)
}
