// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/zentrix-app/zentrix-backend-go-temp/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// BatchCreateSeats mocks base method.
func (m *MockEventRepo) BatchCreateSeats(ctx context.Context, seats []entity.Seat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateSeats", ctx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateSeats indicates an expected call of BatchCreateSeats.
func (mr *MockEventRepoMockRecorder) BatchCreateSeats(ctx, seats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateSeats", reflect.TypeOf((*MockEventRepo)(nil).BatchCreateSeats), ctx, seats)
}

// CreateEvent mocks base method.
func (m *MockEventRepo) CreateEvent(ctx context.Context, event *entity.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEventRepoMockRecorder) CreateEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEventRepo)(nil).CreateEvent), ctx, event)
}

// CreateShow mocks base method.
func (m *MockEventRepo) CreateShow(ctx context.Context, show *entity.Show) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShow", ctx, show)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShow indicates an expected call of CreateShow.
func (mr *MockEventRepoMockRecorder) CreateShow(ctx, show any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShow", reflect.TypeOf((*MockEventRepo)(nil).CreateShow), ctx, show)
}

// CreateVenue mocks base method.
func (m *MockEventRepo) CreateVenue(ctx context.Context, venue *entity.Venue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVenue", ctx, venue)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVenue indicates an expected call of CreateVenue.
func (mr *MockEventRepoMockRecorder) CreateVenue(ctx, venue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVenue", reflect.TypeOf((*MockEventRepo)(nil).CreateVenue), ctx, venue)
}

// GetEventByID mocks base method.
func (m *MockEventRepo) GetEventByID(ctx context.Context, id string) (entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByID", ctx, id)
	ret0, _ := ret[0].(entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByID indicates an expected call of GetEventByID.
func (mr *MockEventRepoMockRecorder) GetEventByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByID", reflect.TypeOf((*MockEventRepo)(nil).GetEventByID), ctx, id)
}

// GetSeatsByShowID mocks base method.
func (m *MockEventRepo) GetSeatsByShowID(ctx context.Context, showID string) ([]entity.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatsByShowID", ctx, showID)
	ret0, _ := ret[0].([]entity.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatsByShowID indicates an expected call of GetSeatsByShowID.
func (mr *MockEventRepoMockRecorder) GetSeatsByShowID(ctx, showID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatsByShowID", reflect.TypeOf((*MockEventRepo)(nil).GetSeatsByShowID), ctx, showID)
}

// GetShowByID mocks base method.
func (m *MockEventRepo) GetShowByID(ctx context.Context, id string) (entity.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShowByID", ctx, id)
	ret0, _ := ret[0].(entity.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShowByID indicates an expected call of GetShowByID.
func (mr *MockEventRepoMockRecorder) GetShowByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShowByID", reflect.TypeOf((*MockEventRepo)(nil).GetShowByID), ctx, id)
}

// GetShowsByEventID mocks base method.
func (m *MockEventRepo) GetShowsByEventID(ctx context.Context, eventID string) ([]entity.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShowsByEventID", ctx, eventID)
	ret0, _ := ret[0].([]entity.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShowsByEventID indicates an expected call of GetShowsByEventID.
func (mr *MockEventRepoMockRecorder) GetShowsByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShowsByEventID", reflect.TypeOf((*MockEventRepo)(nil).GetShowsByEventID), ctx, eventID)
}

// GetVenueByID mocks base method.
func (m *MockEventRepo) GetVenueByID(ctx context.Context, id string) (entity.Venue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVenueByID", ctx, id)
	ret0, _ := ret[0].(entity.Venue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVenueByID indicates an expected call of GetVenueByID.
func (mr *MockEventRepoMockRecorder) GetVenueByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVenueByID", reflect.TypeOf((*MockEventRepo)(nil).GetVenueByID), ctx, id)
}

// ListEvents mocks base method.
func (m *MockEventRepo) ListEvents(ctx context.Context, limit, offset int) ([]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventRepoMockRecorder) ListEvents(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEventRepo)(nil).ListEvents), ctx, limit, offset)
}

// LockSeats mocks base method.
func (m *MockEventRepo) LockSeats(ctx context.Context, showID string, seatIDs []string, userID string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSeats", ctx, showID, seatIDs, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LockSeats indicates an expected call of LockSeats.
func (mr *MockEventRepoMockRecorder) LockSeats(ctx, showID, seatIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSeats", reflect.TypeOf((*MockEventRepo)(nil).LockSeats), ctx, showID, seatIDs, userID)
}
