from enum import StrEnum


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
    PAYMENT_EXPIRED_REFUND_PENDING = "PAYMENT_EXPIRED_REFUND_PENDING"


class TransactionStatus(StrEnum):
    INITIATED = "INITIATED"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class PaymentGateway(StrEnum):
    MOCK = "mock"
    VNPAY = "vnpay"
    MOMO = "momo"
    STRIPE = "stripe"


class KafkaTopics(StrEnum):
    BOOKING_EVENTS = "booking-events"
    PAYMENT_EVENTS = "payment-events"


class ErrorCode(StrEnum):
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_EXPIRED = "PAYMENT_EXPIRED"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    IDEMPOTENT_DUPLICATE = "IDEMPOTENT_DUPLICATE"
